name: cx

on: push

env:
  AWS_REGION: us-east-1
  API_STAGE_NAME: "v0"
  ACCESS_LOG_RETENTION_DAYS: 7
  FUNC_MEMORY_SIZE: 128
  FUNC_TIMEOUT: 5
  FUNC_LOG_RETENTION_DAYS: 7

defaults:
  run:
    shell: "/bin/bash {0}"

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CFN_TEMPLATES: "stack.yml\n.github/cd_setup.yml\n"
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.1

      - uses: aws-actions/configure-aws-credentials@v1.4.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: validate all cloudformation templates
        run: |
          printf "${{ env.CFN_TEMPLATES }}" | while read template; do
            aws cloudformation validate-template \
              --template-body="file://$template"
          done

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      _stack_name: ${{ steps.configure_environment.outputs._stack_name }}
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.1

      - name: map branch 2 test/prod
        run: |
          if [[ ${{ github.ref }} == *master ]]; then
            echo ::set-env name=_ENVIRONMENT::test
          else
            echo ::set-env name=_ENVIRONMENT::test
          fi

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: configure the environment
        id: configure_environment
        run: |
          echo "::set-env name=_STACK_NAME::chale-$_ENVIRONMENT"
          echo "::set-env name=_READ_PROFILE_HANDLER_NAME::chale-$_ENVIRONMENT-readprofilehandler"
          echo "::set-env name=_UPSERT_PROFILE_HANDLER_NAME::chale-$_ENVIRONMENT-upsertprofilehandler"
          echo "::set-output name=_stack_name::chale-$_ENVIRONMENT"

      - name: deploy the core stack
        run: |
          aws cloudformation deploy \
            --template-file=./stack.yml \
            --stack-name=${{ env._STACK_NAME }} \
            --parameter-overrides \
              Environment=${{ env._ENVIRONMENT }} \
              ApiStageName=${{ env.API_STAGE_NAME }} \
              FunctionMemorySize=${{ env.FUNC_MEMORY_SIZE }} \
              FunctionTimeout=${{ env.FUNC_TIMEOUT}} \
              FunctionLogRetentionInDays=${{ env.FUNC_LOG_RETENTION_DAYS }} \
              AccessLogRetentionInDays=${{ env.ACCESS_LOG_RETENTION_DAYS }} \
              ReadProfileHandlerName=${{ env._READ_PROFILE_HANDLER_NAME }} \
              UpsertProfileHandlerName=${{ env._UPSERT_PROFILE_HANDLER_NAME }} \
            --capabilities=CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: deploy the read profile handler
        run: |
          code_size=$( \
            aws lambda get-function-configuration \
              --function-name=${{ env._READ_PROFILE_HANDLER_NAME }} \
              --query=CodeSize \
          )
          if ! git diff HEAD HEAD~1 -s --exit-code "./lambdas/profile/read/*" || \
             (( $code_size < 419 ));
          then
            cd ./lambdas/profile/read
            npm ci --only=prod
            cd ../../..
            npx @zeit/ncc@0.22.3 build \
              --external=aws-sdk \
              --out=./lambdas/profile/bundles/read \
              ./lambdas/profile/read/index.js
            zip -j /tmp/bundle.zip ./lambdas/profile/bundles/read/index.js
            aws lambda update-function-code \
              --function-name=${{ env._READ_PROFILE_HANDLER_NAME }} \
              --publish \
              --zip-file=fileb:///tmp/bundle.zip
          fi

      - name: deploy the upsert profile handler
        run: |
          code_size=$( \
            aws lambda get-function-configuration \
              --function-name=${{ env._UPSERT_PROFILE_HANDLER_NAME }} \
              --query=CodeSize \
          )
          if ! git diff HEAD HEAD~1 -s --exit-code "./lambdas/profile/upsert/*" || \
             (( $code_size < 419 ));
          then
            cd ./lambdas/profile/upsert
            npm ci --only=prod
            cd ../../..
            npx @zeit/ncc@0.22.3 build \
              --external=aws-sdk \
              --out=./lambdas/profile/bundles/upsert \
              ./lambdas/profile/upsert/index.js
            zip -j /tmp/bundle.zip ./lambdas/profile/bundles/upsert/index.js
            aws lambda update-function-code \
              --function-name=${{ env._UPSERT_PROFILE_HANDLER_NAME }} \
              --publish \
              --zip-file=fileb:///tmp/bundle.zip
          fi


  test:
    runs-on: ubuntu-latest
    needs:
      - validate
      - deploy
    steps:
      - uses: actions/checkout@v2.3.1

      - uses: aws-actions/configure-aws-credentials@v1.4.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: fetch stack outputs
        run: |
          api_base_url="$( \
            aws cloudformation describe-stacks \
              --stack-name="${{ needs.deploy.outputs._stack_name }}" \
              --query="Stacks[0].Outputs[?OutputKey=='ApiBaseURL'].OutputValue" \
              --output=text \
          )"
          echo "::set-env name=_BASE_URL::$api_base_url"
      - name: api testing
        run: |
          printf "[DEBUG] api base url: %s\n" "$_BASE_URL"
          source ./test/api_test.sh
          test_profile_read_200
