name: cx

on: push

env:
  AWS_REGION: us-east-1
  ACCESS_LOG_RETENTION_DAYS: 7
  FUNC_MEMORY_SIZE: 128
  FUNC_TIMEOUT: 5
  FUNC_LOG_RETENTION_DAYS: 7

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CFN_TEMPLATES: "stack.yml\n.github/cd_setup.yml\n"
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: validate all cloudformation templates
        run: |
          printf "${{ env.CFN_TEMPLATES }}" | while read template; do
            aws cloudformation validate-template \
              --template-body="file://$template"
          done

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      _stack_name: ${{ steps.configure_environment.outputs._stack_name }}
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: map branch 2 test/prod
        run: |
          if [[ ${{ github.ref }} == *main ]]; then
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
          fi

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: configure the environment
        id: configure_environment
        run: |

          echo "STACK_NAME=tcjam-$ENVIRONMENT" >> $GITHUB_ENV
          echo "READ_PROFILE_HANDLER_NAME=tcjam-$ENVIRONMENT-readprofilehandler" >> $GITHUB_ENV
          echo "UPSERT_PROFILE_HANDLER_NAME=tcjam-$ENVIRONMENT-upsertprofilehandler" >> $GITHUB_ENV
          echo "DELETE_PROFILE_HANDLER_NAME=tcjam-$ENVIRONMENT-deleteprofilehandler" >> $GITHUB_ENV
          echo "PUBLIC_BUCKET_NAME=tcjam-$ENVIRONMENT-public-bucket" >> $GITHUB_ENV
          echo "::set-output name=_stack_name::tcjam-$ENVIRONMENT"

      - name: deploy the core stack
        run: |
          aws cloudformation deploy \
            --template-file=./stack.yml \
            --stack-name=${{ env.STACK_NAME }} \
            --parameter-overrides \
              PublicBucketName=${{ env.PUBLIC_BUCKET_NAME }} \
              Environment=${{ env.ENVIRONMENT }} \
              FunctionMemorySize=${{ env.FUNC_MEMORY_SIZE }} \
              FunctionTimeout=${{ env.FUNC_TIMEOUT}} \
              FunctionLogRetentionInDays=${{ env.FUNC_LOG_RETENTION_DAYS }} \
              AccessLogRetentionInDays=${{ env.ACCESS_LOG_RETENTION_DAYS }} \
              ReadProfileHandlerName=${{ env.READ_PROFILE_HANDLER_NAME }} \
              UpsertProfileHandlerName=${{ env.UPSERT_PROFILE_HANDLER_NAME }} \
              DeleteProfileHandlerName=${{ env.DELETE_PROFILE_HANDLER_NAME }} \
            --capabilities=CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: deploy the upsert profile handler
        run: |
          code_size=$( \
            aws lambda get-function-configuration \
              --function-name=${{ env.UPSERT_PROFILE_HANDLER_NAME }} \
              --query=CodeSize \
          )
          if ! git diff HEAD HEAD~1 --exit-code -s "./lambdas/profiles/upsert/*" || \
             (( $code_size < 419 ));
          then
            cd ./lambdas/profiles/upsert
            npm ci --only=prod
            cd ../../..
            npx @zeit/ncc@0.22.3 build \
              --external=aws-sdk \
              --out=./lambdas/profiles/bundles/upsert \
              ./lambdas/profiles/upsert/index.js
            zip -j /tmp/bundle.zip ./lambdas/profiles/bundles/upsert/index.js
            aws lambda update-function-code \
              --function-name=${{ env.UPSERT_PROFILE_HANDLER_NAME }} \
              --publish \
              --zip-file=fileb:///tmp/bundle.zip
          fi

      - name: deploy the read profile handler
        run: |
          code_size=$( \
            aws lambda get-function-configuration \
              --function-name=${{ env.READ_PROFILE_HANDLER_NAME }} \
              --query=CodeSize \
          )
          if ! git diff HEAD HEAD~1 --exit-code -s "./lambdas/profiles/read/*" || \
             (( $code_size < 419 ));
          then
            cd ./lambdas/profiles/read
            npm ci --only=prod
            cd ../../..
            npx @zeit/ncc@0.22.3 build \
              --external=aws-sdk \
              --out=./lambdas/profiles/bundles/read \
              ./lambdas/profiles/read/index.js
            zip -j /tmp/bundle.zip ./lambdas/profiles/bundles/read/index.js
            aws lambda update-function-code \
              --function-name=${{ env.READ_PROFILE_HANDLER_NAME }} \
              --publish \
              --zip-file=fileb:///tmp/bundle.zip
          fi

      - name: deploy the delete profile handler
        run: |
          code_size=$( \
            aws lambda get-function-configuration \
              --function-name=${{ env.DELETE_PROFILE_HANDLER_NAME }} \
              --query=CodeSize \
          )
          if ! git diff HEAD HEAD~1 --exit-code -s "./lambdas/profiles/delete/*" || \
             (( $code_size < 419 ));
          then
            cd ./lambdas/profiles/delete
            npm ci --only=prod
            cd ../../..
            npx @zeit/ncc@0.22.3 build \
              --external=aws-sdk \
              --out=./lambdas/profiles/bundles/delete \
              ./lambdas/profiles/delete/index.js
            zip -j /tmp/bundle.zip ./lambdas/profiles/bundles/delete/index.js
            aws lambda update-function-code \
              --function-name=${{ env.DELETE_PROFILE_HANDLER_NAME }} \
              --publish \
              --zip-file=fileb:///tmp/bundle.zip
          fi

  test:
    runs-on: ubuntu-latest
    needs:
      - validate
      - deploy
    steps:
      - uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: api testing
        run: |
          source <(curl -sSf https://raw.githubusercontent.com/chiefbiiko/bashert/v1.0.1/bashert.sh)
          source ./test_suite.sh
          test_profiles_upsert_204
          test_profiles_upsert_400
          test_profiles_read_200
          test_profiles_read_400
          test_profiles_read_404
          test_profiles_delete_204
          test_profiles_delete_400
          
